name: build & format

on: 
    push: 
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: install dependencies
              run: yarn

            - name: format with prettier
              run: yarn format
            
            - name: build code
              run: yarn build
